### PR TITLE
Fullscreen Projector Fix on MacOS

### PR DESCRIPTION
**Pull request by wvabrinskas**
**Problem**
- Fullscreen projector was not fullscreen on macOS and continued to show the frame with the window buttons. 

**Solution** 
- Set `fullScreenable` to `true` on `BrowserWindow`
- Seems too simple.... 

**Tested**
- M1 Mac Mini Big Sur 11.3 RC

### CODE REVIEW

**Comment by MegoyTambayan** [comment]
I don't know How to Start

**Comment by wvabrinskas** [comment]
> I don't know How to Start

The instructions are in the README of the repo.

**Comment by trevorrl** [comment]
I tested this locally on an Intel Macbook Pro running Catalina and it doesn't seem to have changed the behavior. Adding this one line lets you full-screen the projector window on Big Sur?

**Comment by wvabrinskas** [comment]
> I tested this locally on an Intel Macbook Pro running Catalina and it doesn't seem to have changed the behavior. Adding this one line lets you full-screen the projector window on Big Sur?

It does actually. I haven't tested on Catalina but Big Sur it works perfectly. I sadly don't have a catalina device to test.

**Comment by wvabrinskas** [comment]
@trevorrl I managed to get a Catalina device and I'm seeing my fix work properly. 
Screen Shot 2021-05-06 at 4 45 08 PM

Not sure what's going on on your end =(

**Comment by andycreeth** [comment]
@wvabrinskas Want to apologize for letting this PR drop off our radar.  I am able to reproduce this issue on Catalina and this fixes the issue.  In the meantime since you opened this PR we've actually ported this code from Vue to React.  I've opened a separate PR with this change applied to the new component here: https://github.com/stream-labs/desktop/pull/4014.  I carried over your original commits so you will still get credit.  Thank you for finding the solution here, and sorry again for letting this one sit so long.  Cheers.

**Comment by wvabrinskas** [comment]
@andycreeth no worries! Thanks for taking a look at my fix!

**Pull request closed without merging**
