### PR TITLE
Added support for virtual camera toggle hot key

### PR DESCRIPTION
**Pull request by ryanfalzon**

### CODE REVIEW

**Review by gettinToasty — APPROVED** [review]

**Comment by ryanfalzon** [comment]
@gettinToasty do I need to close the PR myself? Have the changes been merged?

**Comment by gettinToasty** [comment]
@ryanfalzon Hey! They haven't been merged yet, I need to investigate why our test suite isn't running on this PR. Thanks for the addition though!

**Comment by ryanfalzon** [comment]
@gettinToasty I might have a problem. It is saying that I have not signed the CLA with account 'Ryan Falzon'. I have successfully signed the CLA but it still marks as pending. Any clues as to what might have happened?

**Pull request merged**
